### ISSUE TITLE
problem of genotype matrix

### ISSUE THREAD

**Issue by cz354** [WenjianBI/SPACox#1]
Hi,

I have a question about the genotype matrix. Since Geno.mtx is a numeric genotype matrix here, it will be too large when I have 8299079 genetic variants and about 6000 individuals. I don't know how to solve this problem. And is it possible to use binary genotype files?

Best,
Chi

**Comment by WenjianBI** [comment]
Hi Chi,

Currently, I suggest using some tools such as R package 'seqminer' to split the binary genotype files into multiple chunks and then pass each chunk to SPACox function. Using this approach, you can also apply parallel computing easily.  

Thanks,
Wenjian

**Comment by WenjianBI** [comment]
Hi Chi,

I just updated the package to 0.1.2 in which package 'seqminer' is used so that plink files can be used as input. Can you help check if the new function SPACox.plink() works well? Please let me know is anything unexpected happens.

Thanks,
Wenjian

**Comment by cz354** [comment]
Hi Wenjian,

Thank you for your reply and update. I will try the new function.

Beat,
Chi

**Comment by cz354** [comment]
Hi Wenjian,

I have tried the new function and it finished successfully. Thank you again.

Best regards,
Chi

**Comment by WenjianBI** [comment]
You are welcome. If any other questions, please feel free to let me know. BTW, this morning I modified a little for missing genotype data in plink files. Please check it and make assure you are using the updated version. https://github.com/WenjianBI/SPACox/commit/39c6cd5157009e61cd0e4134444b416174937021
